// Auto-generated from OpenPrintTag spec — do not edit manually
// Regenerate: python3 scripts/generate_types.py

package cool.nfc.openprinttag.types

/** Material property tags */
enum class MaterialPropertyTag(
    val id: Int,
    val displayName: String,
    val category: TagCategory
) {
    FILTRATION_RECOMMENDED(0, "Filtration recommended", TagCategory.BIOLOGICAL),
    BIOCOMPATIBLE(1, "Biocompatible", TagCategory.BIOLOGICAL),
    HOME_COMPOSTABLE(61, "Home compostable", TagCategory.BIOLOGICAL),
    INDUSTRIALLY_COMPOSTABLE(62, "Industrially compostable", TagCategory.BIOLOGICAL),
    BIO_BASED(63, "Bio-based", TagCategory.BIOLOGICAL),
    ANTIBACTERIAL(2, "Antibacterial", TagCategory.BIOLOGICAL),
    AIR_FILTERING(3, "Air filtering", TagCategory.BIOLOGICAL),
    ABRASIVE(4, "Abrasive", TagCategory.PHYSICAL),
    FOAMING(5, "Foaming", TagCategory.PHYSICAL),
    CASTABLE(67, "Castable", TagCategory.PHYSICAL),
    SELF_EXTINGUISHING(6, "Self-extinguishing", TagCategory.PHYSICAL),
    PARAMAGNETIC(7, "Paramagnetic", TagCategory.PHYSICAL),
    RADIATION_SHIELDING(8, "Radiation shielding", TagCategory.PHYSICAL),
    HIGH_TEMPERATURE(9, "High temperature", TagCategory.PHYSICAL),
    HIGH_SPEED(71, "High speed", TagCategory.PHYSICAL),
    ESD_SAFE(10, "ESD safe", TagCategory.ELECTRICAL),
    CONDUCTIVE(11, "Conductive", TagCategory.ELECTRICAL),
    EMI_SHIELDING(70, "EMI shielding", TagCategory.ELECTRICAL),
    BLEND(12, "Blend", TagCategory.CHEMICAL),
    WATER_SOLUBLE(13, "Water soluble", TagCategory.CHEMICAL),
    IPA_SOLUBLE(14, "IPA soluble", TagCategory.CHEMICAL),
    LIMONENE_SOLUBLE(15, "Limonene soluble", TagCategory.CHEMICAL),
    LOW_OUTGASSING(64, "Low outgassing", TagCategory.CHEMICAL),
    MATTE(16, "Matte", TagCategory.VISUAL),
    SILK(17, "Silk", TagCategory.VISUAL),
    TRANSLUCENT(19, "Translucent", TagCategory.VISUAL),
    TRANSPARENT(20, "Transparent", TagCategory.VISUAL),
    WITHOUT_PIGMENTS(65, "Without pigments", TagCategory.VISUAL),
    IRIDESCENT(21, "Iridescent", TagCategory.VISUAL),
    PEARLESCENT(22, "Pearlescent", TagCategory.VISUAL),
    GLITTER(23, "Glitter", TagCategory.VISUAL),
    GLOW_IN_THE_DARK(24, "Glow in the dark", TagCategory.VISUAL),
    NEON(25, "Neon", TagCategory.VISUAL),
    ILLUMINESCENT_COLOR_CHANGE(26, "Illuminescent color change", TagCategory.VISUAL),
    TEMPERATURE_COLOR_CHANGE(27, "Temperature color change", TagCategory.VISUAL),
    GRADUAL_COLOR_CHANGE(28, "Gradual color change", TagCategory.VISUAL),
    COEXTRUDED(29, "Coextruded", TagCategory.VISUAL),
    CONTAINS_CARBON(30, "Contains carbon", TagCategory.ADDITIVES_OTHER),
    CONTAINS_CARBON_FIBER(31, "Contains carbon fiber", TagCategory.ADDITIVES_OTHER),
    CONTAINS_CARBON_NANO_TUBES(32, "Contains carbon nano tubes", TagCategory.ADDITIVES_OTHER),
    CONTAINS_GRAPHENE(72, "Contains graphene", TagCategory.ADDITIVES_OTHER),
    CONTAINS_GLASS(33, "Contains glass", TagCategory.ADDITIVES_OTHER),
    CONTAINS_GLASS_FIBER(34, "Contains glass fiber", TagCategory.ADDITIVES_OTHER),
    CONTAINS_KEVLAR(35, "Contains Kevlar", TagCategory.ADDITIVES_OTHER),
    CONTAINS_PTFE(68, "Contains PTFE", TagCategory.ADDITIVES_OTHER),
    CONTAINS_STONE(36, "Contains stone", TagCategory.ADDITIVES_OTHER),
    CONTAINS_MAGNETITE(37, "Contains magnetite", TagCategory.ADDITIVES_OTHER),
    CONTAINS_ORGANIC_MATERIAL(38, "Contains organic material", TagCategory.ADDITIVES_ORGANIC),
    CONTAINS_CORK(39, "Contains cork", TagCategory.ADDITIVES_ORGANIC),
    CONTAINS_WAX(40, "Contains wax", TagCategory.ADDITIVES_ORGANIC),
    CONTAINS_WOOD(41, "Contains wood", TagCategory.ADDITIVES_ORGANIC),
    CONTAINS_ALGAE(66, "Contains algae", TagCategory.ADDITIVES_ORGANIC),
    CONTAINS_BAMBOO(42, "Contains bamboo", TagCategory.ADDITIVES_ORGANIC),
    CONTAINS_PINE(43, "Contains pine", TagCategory.ADDITIVES_ORGANIC),
    CONTAINS_CERAMIC(44, "Contains ceramic", TagCategory.ADDITIVES_OTHER),
    CONTAINS_BORON_CARBIDE(45, "Contains boron carbide", TagCategory.ADDITIVES_OTHER),
    CONTAINS_METAL(46, "Contains metal", TagCategory.ADDITIVES_METAL),
    CONTAINS_BRONZE(47, "Contains bronze", TagCategory.ADDITIVES_METAL),
    CONTAINS_IRON(48, "Contains iron", TagCategory.ADDITIVES_METAL),
    CONTAINS_STEEL(49, "Contains steel", TagCategory.ADDITIVES_METAL),
    CONTAINS_SILVER(50, "Contains silver", TagCategory.ADDITIVES_METAL),
    CONTAINS_COPPER(51, "Contains copper", TagCategory.ADDITIVES_METAL),
    CONTAINS_ALUMINIUM(52, "Contains aluminium", TagCategory.ADDITIVES_METAL),
    CONTAINS_BRASS(53, "Contains brass", TagCategory.ADDITIVES_METAL),
    CONTAINS_TUNGSTEN(54, "Contains tungsten", TagCategory.ADDITIVES_METAL),
    IMITATES_WOOD(55, "Imitates wood", TagCategory.IMITATION),
    IMITATES_METAL(56, "Imitates metal", TagCategory.IMITATION),
    IMITATES_MARBLE(57, "Imitates marble", TagCategory.IMITATION),
    IMITATES_STONE(58, "Imitates stone", TagCategory.IMITATION),
    LITHOPHANE(59, "Lithophane", TagCategory.OTHER),
    RECYCLED(60, "Recycled", TagCategory.OTHER),
    LIMITED_EDITION(69, "Limited edition", TagCategory.OTHER);

    companion object {
        fun fromId(id: Int): MaterialPropertyTag? = entries.find { it.id == id }
        fun forCategory(category: TagCategory): List<MaterialPropertyTag> = entries.filter { it.category == category }
    }
}
